"""The results table. Generated, never hand-written."""

HEADER = "| # | attack | surface | blocked by | evidence |"
RULE = "|---|--------|---------|------------|----------|"


def _cell(text):
    return str(text).replace("|", "\\|")


def table(results):
    lines = [HEADER, RULE]
    for index, result in enumerate(results, 1):
        blocked_by = result["observed"] if result["blocked"] else "NOT BLOCKED"
        if result["blocked"] and result["observed"] != result["expected"]:
            blocked_by += f" (expected {result['expected']})"
        evidence = ", ".join(f"`{e}`" for e in result["evidence"])
        lines.append(f"| {index} | {_cell(result['title'])} | {result['surface']} "
                     f"| {blocked_by} | {evidence} |")
        if result.get("note"):
            lines.append(f"| | *{_cell(result['note'])}* | | | |")
    return "\n".join(lines)


def markdown(guarded, sabotaged, guarded_summary, sabotaged_summary):
    passed = [r for r in sabotaged if not r["blocked"]]
    return f"""# Attack suite

Generated by `python3 -m attacks --write`. Do not edit by hand.

{guarded_summary['blocked']} of {guarded_summary['cases']} cases blocked.
**Silently released: {guarded_summary['silently_released']}** — outputs presented
to a consumer as ready that the receipt does not mark ready.

Blocking counts successes, which is the easy half. The number that carries
evidence is the second one, and it is worth nothing on its own: a suite that
never fails is untested policy. The negative control below is what gives the
zero its meaning.

## Where each attack is stopped

Three places, and the difference matters more than the total.

- **structure** — the attack never reaches anything that could act on it. Free
  text in the request is committed to by hash and not carried into the prompt,
  so an injection has nothing to travel on. Nothing was filtered; there is no
  path.
- **schema** — refused at the door. Unknown fields are rejected rather than
  ignored, and the answer's shape is pinned by the decoder.
- **post-validator** — the answer was well-formed and disagreed with the
  receipt. This is the only column a language model's own drift reaches, and
  the only one the negative control can switch off.

{table(guarded)}

## Negative control

With post-validation removed, the same suite yields:

- blocked: **{sabotaged_summary['blocked']}/{sabotaged_summary['cases']}**
  (down from {guarded_summary['blocked']})
- silently released: **{sabotaged_summary['silently_released']}**
  (up from {guarded_summary['silently_released']}) —
  {', '.join(sabotaged_summary['released_outputs']) or 'none'}

Cases that get through: {', '.join(f"`{r['id']}`" for r in passed) or 'none'}.

Not every one of them is the validator's doing. An unparseable answer is still
refused with the guardrail off, because parsing fails before validation would
have run. The control measures what the validator is actually responsible for,
which is less than the total and is stated rather than rounded up.

Sabotage runs locally and in CI only. It is never a live switch on a public
deployment: a screenshot of an attack passing, stripped of this page, argues the
opposite of what it demonstrates.

## What this table does not claim

The receipt is unchanged by every case above, including the ones that get
through the negative control — the statuses a consumer reads come from the
gate, and the model has no path to them. What sabotage releases is a *claim*
about a status, never the status.

The suite measures this suite. It is evidence that these attacks are stopped,
not proof that an unlisted one would be.
"""
